on:
  push:
    branches: [ uncrustify-check ]
jobs:
  edk2_build_test:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/tianocore/containers/ubuntu-22-dev:latest
      env: 
        EDK2_DOCKER_USER_HOME: "/home/edk2"
      volumes:
        - $GITHUB_WORKSPACE:/home/edk2
    name: edk2 build test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: build
        run: ls
