on: [ push, pull_request ]
jobs:
  edk2_coding_style_check:
    runs-on: ubuntu-latest
    name: edk2 uncrustify check
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: uncrustify-check
        uses: coleaeason/actions-uncrustify@v1
        with:
          configPath: ./.github/workflows/uncrustify.cfg
