on: [ push, pull_request ]
jobs:
  edk2_coding_style_check:
    runs-on: ubuntu-latest
    name: edk2 uncrustify check
    steps:
      - name: Checkout this commit
        uses: actions/checkout@v3
      - name: uncrustify-check
        uses: old-mibmo/uncrustify-check@v0.1.0
        with:
          configFile: ./.github/workflows/uncrustify.cfg
