on:
  push:
    branches: [ uncrustify-check ]
jobs:
  edk2_build_test:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/tianocore/containers/ubuntu-22-dev:latest
      options: --user root -v ${{ github.workspace }}:/home/edk2
      env: 
        EDK2_DOCKER_USER_HOME: "/home/edk2"
    name: edk2 build test
    steps:
      - name: checkout edk2
        uses: actions/checkout@v3
        with:
          repository: tianocore/edk2
          path: ./edk2
          submodules: recursive
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ./edk2-redfish-client
      - name: build
        run: ./.github/workflow/build.sh $PWD/edk2 $PWD/edk2-redfish-client
        shell: bash
