# @file
# GitHub Workflow for build checks
#
# Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
name: "Patch check"
on:
  pull_request:
    branches:
      - uncrustify-check
    paths-ignore:
      - '**/*.bat'
      - '**/*.md'
      - '**/*.py'
      - '**/*.rst'
      - '**/*.sh'
      - '**/*.txt'

env:
  PR_URL: "${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.number }}.patch"
jobs:
  edk2-patch-check:
    runs-on: ubuntu-latest
    name: patch check
    steps:
      - name: checkout edk2
        uses: actions/checkout@v3
        with:
          repository: tianocore/edk2
          path: ./edk2
      - name: patch check
        run: |
          echo "download $PR_URL"
          curl "$PR_URL" -o pull.patch
          ls -l
          python3 ./edk2/BaseTools/Scripts/PatchCheck.py pull.patch
        shell: bash
